"""Write `design-system/screen-translator/tokens.md` from the code.

Generated rather than hand-maintained, and checked by a test that the
file on disk equals what this script produces. A token table that can
drift from the implementation is worse than no table: it is confidently
wrong.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from screen_translator.design import metrics, semantic, typography  # noqa: E402
from screen_translator.design.primitives import contrast_ratio  # noqa: E402
from screen_translator.version import __version__  # noqa: E402

OUTPUT = PROJECT_ROOT / "design-system" / "screen-translator" / "tokens.md"

COLOUR_ROLES = (
    "bg_canvas",
    "bg_surface",
    "bg_surface_raised",
    "bg_hover",
    "bg_pressed",
    "bg_disabled",
    "text_primary",
    "text_secondary",
    "text_disabled",
    "text_on_accent",
    "stroke_separator",
    "stroke_control",
    "accent_fill",
    "accent_fill_hover",
    "accent_fill_pressed",
    "accent_text",
    "critical",
    "success",
    "caution",
    "focus",
    "selection_bg",
    "selection_text",
    "tooltip_bg",
    "tooltip_text",
)

METRIC_FIELDS = (
    "radius_card",
    "radius_group_row",
    "radius_control",
    "radius_small",
    "radius_pill",
    "border",
    "focus_border",
    "rule",
    "space_hair",
    "space_tight",
    "space_row",
    "space_card",
    "space_section",
    "space_page",
    "height_primary",
    "height_control",
    "height_icon",
    "height_tab",
)


def render() -> str:
    lines = [
        "# Tokens",
        "",
        "> Generated by `scripts/generate_tokens_doc.py`. Do not edit by hand;",
        "> `test_the_token_document_matches_the_code` fails if this drifts.",
        "",
        f"**Version:** {__version__}",
        "",
        "## Colour",
        "",
        "| Role | Light | Dark | Currently shipping |",
        "|---|---|---|---|",
    ]
    for role in COLOUR_ROLES:
        lines.append(
            f"| `{role}` | `{getattr(semantic.LIGHT, role)}` "
            f"| `{getattr(semantic.DARK, role)}` "
            f"| `{getattr(semantic.CONSTRUCTIVIST, role)}` |"
        )

    lines += [
        "",
        "## Contrast",
        "",
        "Text against every surface it can appear on. AA needs 4.5:1.",
        "",
        "| Pair | Light | Dark |",
        "|---|---|---|",
    ]
    for text_role in ("text_primary", "text_secondary", "critical", "success", "caution"):
        for surface in ("bg_canvas", "bg_surface", "bg_surface_raised"):
            light = contrast_ratio(
                getattr(semantic.LIGHT, text_role), getattr(semantic.LIGHT, surface)
            )
            dark = contrast_ratio(
                getattr(semantic.DARK, text_role), getattr(semantic.DARK, surface)
            )
            lines.append(f"| `{text_role}` on `{surface}` | {light:.2f} | {dark:.2f} |")
    on_accent_light = contrast_ratio(semantic.LIGHT.text_on_accent, semantic.LIGHT.accent_fill)
    on_accent_dark = contrast_ratio(semantic.DARK.text_on_accent, semantic.DARK.accent_fill)
    lines.append(
        f"| `text_on_accent` on `accent_fill` | {on_accent_light:.2f} | {on_accent_dark:.2f} |"
    )

    lines += ["", "## Geometry", "", "| Metric | Rounded | Currently shipping |", "|---|---|---|"]
    for field in METRIC_FIELDS:
        lines.append(
            f"| `{field}` | {getattr(metrics.ROUNDED, field)} "
            f"| {getattr(metrics.FLAT, field)} |"
        )

    lines += [
        "",
        "## Typography",
        "",
        f"- Display: {', '.join(typography.APPLE.display)}",
        f"- Text: {', '.join(typography.APPLE.text)}",
        f"- Weights: {', '.join(str(weight) for weight in typography.ALLOWED_WEIGHTS)}",
        f"- Display threshold: {typography.DISPLAY_THRESHOLD}px",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8", newline="\n")
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
